# Model
seed: 42  # Seed for reproducibility
n_input: 40  # Number of input features
n_output: 13  # Number of output features
n_hidden_layers: 8
n_hidden_neurons: 256
max_epochs: 100  # Maximum number of epochs
lr: 1.e-4

# Training logging
wandb:
  entity: 'tremblaybenoit'  # Name of wandb entity
  project: 'PCAPRO'  # Name of wandb project
  group: 'Development'  # Name of wandb group
  job_type: 'Training'  # Nme of wandb job_type
  tags: ['development'] # Run tags
  notes: "Mapping function."
